version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  php:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - './src:/var/www/html'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
