version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    expose:
      - 9000
    volumes:
      - './:/var/www/html'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
  
  composer:
    image: composer:1.9.3
    volumes:
      - './:/var/www/html'
    working_dir: /var/www/html
    command: composer install
